name: wayapay
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  currency_formatter: 
  get: ^4.6.5
  provider: ^6.0.4
  http: 
  flutter_svg:
  intl: ^0.18.1
  # google_fonts:
  google_fonts: 
  # credit_card_field: 
  top_snackbar_flutter: ^2.1.1
  flutter_inappwebview: ^5.7.1
  webview_flutter: ^4.0.7
  rflutter_alert: ^2.0.4
  animated_rotating_widget: ^0.0.2
  fluttertoast: 
  custom_timer: ^0.1.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  google_fonts: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.example.wayapay
        pluginClass: WayapayPlugin
      ios:
        pluginClass: WayapayPlugin


  assets:
     - assets/images/

